### PR TITLE
Implement #respond_to?

### PR DESCRIPTION
**Pull request by aredondo**

### CODE REVIEW

**Comment by lassebunk** [comment]
Thanks for this pull request.
Could you add `respond_to_missing` also?
http://stackoverflow.com/questions/13793060/respond-to-vs-respond-to-missing

**Comment by kenn** [comment]
Can you just merge this patch? I've hit the issue in multiple occasions and most cases work without `respond_to_missing?`.

**Comment by aredondo** [comment]
That's ok. It's patched now as requested.

**Comment by lassebunk** [comment]
Done. Sorry for the waiting time.

**Comment by kenn** [comment]
Thanks @lassebunk - any ETA for a release?

**Comment by lassebunk** [comment]
Done :+1:

**Pull request merged**
