### PR TITLE
Define #key=(value) and #methods on Dish::Plate

### PR DESCRIPTION
**Pull request by erran**
In response to #2: 
- Adds support for #key_name= methods
- Displays the keys in #methods

### CODE REVIEW

**Comment by lassebunk** [comment]
Thanks for this pull request.
Could you explain a little about the `camel_case_key` method? I think this is a good idea but we need to let the user decide.

**Comment by erran** [comment]
@lassebunk I completely agree. It shouldn't even be in this patch. :surprised: Copy and paste fail I suppose. I'll update the patch and remove the `camel_case_key` method.

I'm working with an API that returns camel case keys, so adding a conversion makes sense there. Not sure how we should implement it in the upstream project though.

**Comment by lassebunk** [comment]
Nice :)
I'm for the case conversions. Could you open op a separate issue so we can discuss it?
Thanks.

**Comment by erran** [comment]
@lassebunk Removed `camel_case_key` in e780eea

**Comment by lassebunk** [comment]
Thanks @erran :+1:. Sorry for the long waiting time.

**Comment by erran** [comment]
@lassebunk No problem!

**Pull request merged**
